data<-read.csv("household_power_consumption.txt",sep=";",na.strings=c("?",""))
subdata<-data[grepl("^[1,2]/2/2007",as.character(data$Date)),]
datatime<-paste(subdata$Date,subdata$Time,sep=",")
datatime<-strptime(datatime,format="%d/%m/%Y,%H:%M:%S")
par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(datatime,subdata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(datatime,subdata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(datatime,subdata$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(datatime,subdata$Sub_metering_2,type="l",col="red")
points(datatime,subdata$Sub_metering_3,type="l",col="blue")
legend("topright",inset=c(0,-0.1),legend=c("sub_metering_1","sub_metering_2","sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=2,box.col="transparent",bty="n",y.intersp=0.3,cex=0.75,yjust=0.5)
plot(datatime,subdata$Global_reactive_power,type="l",xlab="datatime",ylab="Global_reactive_power")
dev.copy(png,filename="plot4.png",width=480,height=480)
dev.off()